services:
  - type: web
    name: movie-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        scope: run
        value: ${MONGODB_URI}
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
